**Day** **1**

In [ ]:
#NUMPY : it is used for numerical computations(calculations)
#features of numpy
# 1) High performance
# 2) Mathmatics, statistical and Linear algebra based concepts
# 4) Enables boradcasting, masking, and vectorization

In [ ]:
#instalation and import statements

#instalation cmd -----> pip install numpy
#import cmd ----> import numpy as np
import numpy as np

In [ ]:
#Array : it is a  homogenous collection of element
#ARRAY creation :
data=[10,20,30,40,50]
a=np.array(data)        #1D ARRAY
print(a)
print(a)
a

[10 20 30 40 50]
[10 20 30 40 50]


array([10, 20, 30, 40, 50])

In [ ]:
b=[[10,20,30],[40,50,60]] #2D
c=np.array(b)
c

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
#arrray atrributes

#shape
a=[[10,20,30],[40,50,60]]
b=np.array(a)
print(b)
b.shape

[[10 20 30]
 [40 50 60]]


(2, 3)

In [ ]:
# 2) ndim : to identify the specific dimenstion(1D or 2D) of an array
b.ndim

2

In [ ]:
# 3) size ---> it is used to display the total number of elements in an array
b.size

6

In [ ]:
#dtype ---> it is used to obtain the datatype of an array elemnts
b.dtype

dtype('int64')

In [ ]:
#itemsize ---> it is used to display bytesize capacity of an array
b.itemsize

8

In [ ]:
#ARRAY CREATION WAYS
# 1) Zeros ---> #it is used to fill folat based zeros to the given rows and columns
# Syntax : np.zeros((row,columns))
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# 1)Ones ---> it is used to fill folat based ones to the given rows and columns
#syntax : np.ones(row,columns)
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# FULL ---> it is used to fill the given value
# Syntax : np.full(rows,column),value)
np.full((4,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
#3 way
#eye ---> it is used to get identity matrix from the identity matrix from the given values
#syntax : np.eye(n) where n is number rows and columns
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 4) Arrange ---> it is used to generate squence of elements for an array
#Syntax : np.arange(start,stop,step)
np.arange(1,10,3)

array([1, 4, 7])

In [ ]:
#Linspace : it is used to create the number of divisions between the given values
#syntax : np.linspace(start,stop,num)
np.linspace(0,1,7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [ ]:
#7 rand --> it is fill random float values in given rows and columns
#note but the values lies between 0 and 1
#syntax np.random.rand(row,col)
np.random.rand(2,3)

array([[0.81528105, 0.4360681 , 0.29934987],
       [0.94971197, 0.50962487, 0.93149257]])

In [ ]:
# 5) randint ---> it is used to fill random values from the given range to given rows and columns
# syntax : np.randint(value1,value2, (row,columns))
np.random.randint(1,10, (2,3))

array([[7, 8, 7],
       [5, 7, 9]])

**Day** 2

In [ ]:

#Accessing elements
a=np.array([[10,20,30],[40,50,60],[70,80,90]]) # 2 D ARRAY
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
a[0,1] #where 0 ----> row index and 1 is column index

np.int64(20)

In [ ]:
#SLICING
#var[SI:EI:UPDATION,SI:EI:UPDATION]
a[0:2,1:]

array([[20, 30],
       [50, 60]])

In [ ]:
#var[SI:EI:UPDATION,COLUMN_INDEX]
a[:,1]

array([20, 50, 80])

In [ ]:
#VAR[ROW_INDEX,SI:EI:UPDATION]
a[2,:2]
#only 2nd row and the 0 and 1 st col gets selected

array([70, 80])

In [ ]:
#arithematic operation
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [ ]:
print(a-b)

[-3 -3 -3]


In [ ]:
print(a*b)

[ 4 10 18]


In [ ]:
print(a/b)

[0.25 0.4  0.5 ]


In [ ]:
print(a**b)

[  1  32 729]


In [ ]:
# U Functions--->Universal Functions
a=np.array([10,20,30])
#1.Square root
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558])

In [ ]:
#2.Exponential
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13])

In [ ]:
#3.log

np.log(a)


array([2.30258509, 2.99573227, 3.40119738])

In [ ]:
#4. sin
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162])

In [ ]:
#5. Sum
np.sum(a)

np.int64(60)

In [ ]:
#6.mean()
np.mean(a)

np.float64(20.0)

In [ ]:
#7.max()
np.max(a)

np.int64(30)

In [ ]:
#8.min()
np.min(a)

np.int64(10)

In [ ]:
#RESHAPE ARRAY
a=np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
a.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
a.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [ ]:
b=a.reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# Flatten----->to convert multidimensional array to 1D array
print(b.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
#STACKING
# 1. HORIZONTAL STACKING
# 2. VERTICAL STACKING

a=np.array([1,2,30])
b=np.array([2,40,60])
print(np.hstack((a,b)))

[ 1  2 30  2 40 60]


In [ ]:
print(np.vstack((a,b)))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [ ]:
# BOOLEAN INDEXING--> Based on the condition we are fetching element from array
a=np.array([6,3,7,18,49,62,99,100,45,50])
a[a%7==0]

In [ ]:
a[a>50]

array([], dtype=int64)

In [ ]:
# Multiple of 6,7,10
a[(a%6==0) & (a%7==0) & (a%10==0)]

In [ ]:
# DATA FILTERING (DEEP COPY) --> The process of obtaining the new address by dropping the old address of an arrray
# MASKING (SHALLOW COPY) --> The process of new layering the main address of an array

a=np.array([1,2,3,4])
b=a.view()   #DEEP COPY : view is the operation used to perform a Deep copy
print(b)

In [ ]:
#MASKING
c=a.copy() #shallow copy